package de.thro.inf.prg3.a07;

import de.thro.inf.prg3.a07.api.OpenMensaAPI;
import de.thro.inf.prg3.a07.model.Meal;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.stage.Stage;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Application
{

	public static void main(String[] args)
	{
		launch(args);
	}

	@Override
	public void start(Stage stage) throws Exception
	{
		Parent root = FXMLLoader.load(getClass().getResource("views/main.fxml"));
		stage.setTitle("Cafeteria");
		stage.setScene(new Scene(root, 800, 600));
		stage.show();

		Retrofit retrofit = new Retrofit.Builder()
			.baseUrl("https://openmensa.org/api/v2/")
			.addConverterFactory(GsonConverterFactory.create())
			.build();

		OpenMensaAPI mensaAPI = retrofit.create(OpenMensaAPI.class);

		Call<Meal[]> call = mensaAPI.getMeals(229, new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(new Date()));

		call.enqueue(new Callback<Meal[]>()
		{
			@Override
			public void onResponse(Call<Meal[]> call, Response<Meal[]> response)
			{
				if (!response.isSuccessful())
					System.out.println(response.body());

				else
					for (Meal meal : response.body())
						System.out.println(meal.getName());
			}

			@Override
			public void onFailure(Call<Meal[]> call, Throwable t)
			{
				System.out.println(t.getMessage());
			}
		});
	}
}
